# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67860d5ea029e3ce97e26e832f7ae59c449e39d32d3e40d170109e4e37a9ced2c04086a392a7dc7af0e463867df9e24f99d02b65bd26da4a6f2e59aa2d50c19f

test:
  secret_key_base: 16bb99885836e563676a98e204885e8c59d750f13b920f6c4a177691d446fe23154528e987093eca620fc87f45763ebcd315f867b5e5095454d1018477f187b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
